// <auto-generated />
using Asiago.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asiago.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240223231800_AddTwitchChannels")]
    partial class AddTwitchChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asiago.Data.Models.GuildConfiguration", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("TwitchUpdateChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigurations");
                });

            modelBuilder.Entity("Asiago.Data.Models.TwitchChannel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("TwitchChannels");
                });

            modelBuilder.Entity("GuildConfigurationTwitchChannels", b =>
                {
                    b.Property<decimal>("SubscribedGuildsGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("TwitchChannelsUserId")
                        .HasColumnType("text");

                    b.HasKey("SubscribedGuildsGuildId", "TwitchChannelsUserId");

                    b.HasIndex("TwitchChannelsUserId");

                    b.ToTable("GuildConfigurationTwitchChannels");
                });

            modelBuilder.Entity("GuildConfigurationTwitchChannels", b =>
                {
                    b.HasOne("Asiago.Data.Models.GuildConfiguration", null)
                        .WithMany()
                        .HasForeignKey("SubscribedGuildsGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asiago.Data.Models.TwitchChannel", null)
                        .WithMany()
                        .HasForeignKey("TwitchChannelsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
