name: Publish Docker image
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    REGISTRY: ghcr.io

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                include:
                    - dockerfile: Dockerfile
                      image: ghcr.io/${{ github.repository }}
                    - dockerfile: Migrations.Dockerfile
                      image: ghcr.io/${{ github.repository }}-migrations

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ matrix.image }}

            - name: Log in to the container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags}}
                labels: ${{ steps.meta.outputs.labels }}
